### PR TITLE
Update to Material-UI v5

### PR DESCRIPTION
**Pull request by 204504bySE**
React is also updated to 17(Material-UI 5 required this)

note: Material-UI 5 requires @emotion/react, @emotion/styled but not automatically installed.
https://mui.com/getting-started/installation/

### CODE REVIEW

**Comment by 204504bySE** [comment]
I confirmed that all storybooks works, by hand.

**Comment by techniq** [comment]
Thanks @204504bySE, looks good to me.  I haven't been using Material-UI on recent projects so I can't confirm too much beyond reviewing the PR, but I don't see anything concerning.

@cvanem Are you still using this project and able to give a quick review?

**Comment by 204504bySE** [comment]
I also migrated storybooks.

With Material-UI 5(continuation of this PR):
https://github.com/204504bySE/mui-virtualized-table/tree/storybook6

With Material-UI 4:
https://github.com/204504bySE/mui-virtualized-table/tree/storybook6-mui4

**Comment by techniq** [comment]
When I tried to `npm install` after merging... it looks like `react-virtualized` is not compatible with react 17...

image

The author of `react-virtualized` also created [react-window](https://github.com/bvaughn/react-window).  Maybe look into using that instead, as it [appears](https://github.com/bvaughn/react-window/blob/master/package.json#L67-L70) to support react 17.

**Comment by 204504bySE** [comment]
Workaround for react-virtualized with React 17 is available.
https://github.com/bvaughn/react-virtualized/issues/1616

e.g. npm install react-virtualized --legacy-peer-deps

**Comment by techniq** [comment]
@204504bySE Hmm... I guess we would need a disclaimer for this since each user would need to know to apply this.  I don't believe `react-window` has a direct replacement for react-virtualized's [MultiGrid](https://github.com/techniq/mui-virtualized-table/blob/master/src/index.js#L3) although I think there are some [examples]( https://github.com/bvaughn/react-window-vs-react-virtualized-synced-grids) so it might still be best to move something that's more supported (although it hasn't had a commit in 6+ months).

Due to my lack of use of the project and thus not being able to provide adequate support, I'm contemplating deprecating the library and referring people to use [react-table](https://react-table.tanstack.com/) (which has [Material-UI](https://react-table.tanstack.com/docs/examples/material-ui-components) examples/support).

Full disclaimer: I have moved away not just from using this library, but also React / Material-UI.  I now use Svelte and have created my own component library ([svelte-ux](https://svelte-ux.vercel.app/)) which has it's own [Table](https://github.com/techniq/svelte-ux/blob/master/src/lib/components/Table.svelte) component (and [action](https://github.com/techniq/svelte-ux/blob/master/src/lib/actions/table.ts)), although it doesn't have windowing (more like [mui-table](https://github.com/techniq/mui-table))  The project itself hasn't been officially announced as I'm still working on the docs (and have another large Svelte library I'm working on as well).

**Comment by cvanem** [comment]
@techniq @204504bySE  Just getting to this now, sorry for the delay! 

It looks like react-virtualized has updated dependencies, but the project owners have yet to release a version which includes the update? A lot of people are asking for it, so not sure why it hasn't been done yet?

I am still using this code for a number of projects and will continue using it where virtual scrolling and dynamic heights are required.   As I am migrating all of my projects to MUI v5 and React 17+ going forward, my biggest concern with not updating this library is having 2 versions of MUI in my webpack.

Here are the options, as I understand them:

1. Wait until react-virtualized publishes a version which includes the updated dependencies.  This may or may not ever happen.
2. Publish mui-virtualized-table v5.0 "pre-release" with a note explaining the usage of --legacy-peer-deps.  If react-virtualized ever publishes a version with the update dependencies, then we can publish an updated official release.
3. Compile necessary react-virtualized code into this project with the updated dependencies.

I vote for option 2 and think it is acceptable given the circumstances.  

@techniq Is this something that can easily be done?  I don't think we ever officially released version 3 (non-beta) but it works great and is still being used.

**Pull request merged**
